CREATE TABLE Students
(
 Id INT IDENTITY PRIMARY KEY NOT NULL
,FirstName NVARCHAR(20) NOT NULL
,MiddleName NVARCHAR(20)
,LastName NVARCHAR(20) NOT NULL
,Age INT  CHECK (Age>=5 AND Age <=100) NOT NULL
,Address NVARCHAR(30)
,Phone NVARCHAR(10) CHECK(LEN(Phone)=10)
)

CREATE TABLE Subjects
(
Id INT IDENTITY PRIMARY KEY NOT NULL
,Name NVARCHAR(20) NOT NULL
,Lessons INT CHECK(Lessons>0) NOT NULL
)

CREATE TABLE StudentsSubjects
(
Id INT IDENTITY PRIMARY KEY
,StudentId INT FOREIGN KEY REFERENCES Students(Id)
,SubjectId INT FOREIGN KEY REFERENCES Subjects(Id)
,Grade DECIMAL(15,2) CHECK(Grade>=2 AND Grade<=6) NOT NULL
)

CREATE TABLE Exams
(
Id INT IDENTITY PRIMARY KEY NOT NULL
,Date DATETIME
,SubjectId INT FOREIGN KEY REFERENCES Subjects(Id)
)

CREATE TABLE StudentsExams
(
StudentId INT  REFERENCES Students(Id) NOT NULL
,ExamId INT REFERENCES Exams(Id) NOT NULL
,Grade DECIMAL(15,2) CHECK(Grade>=2 AND Grade<=6) NOT NULL
)

ALTER TABLE StudentsExams
ADD CONSTRAINT PK_StudentsExams PRIMARY KEY(StudentId,ExamId)


CREATE TABLE Teachers
(
Id INT IDENTITY PRIMARY KEY NOT NULL
,FirstName NVARCHAR(20) NOT NULL
,LastName NVARCHAR(20) NOT NULL
,Address NVARCHAR(20) NOT NULL
,Phone  NVARCHAR(10) CHECK(LEN(Phone)=10)
,SubjectId INT FOREIGN KEY REFERENCES Subjects(Id)
)

CREATE TABLE StudentsTeachers
(
StudentId INT FOREIGN KEY REFERENCES Students(Id) NOT NULL
,TeacherId INT FOREIGN KEY REFERENCES Teachers(Id) NOT NULL

CONSTRAINT PK_StudentsTeachers PRIMARY KEY (StudentId, TeacherId),

)

