--CREATE DATABASE Bakery
--USE BAKERY

CREATE TABLE Countries
(
	Id INT PRIMARY KEY IDENTITY 
	,Name NVARCHAR(50) UNIQUE 
)

CREATE TABLE Customers
(
	Id INT PRIMARY KEY IDENTITY
	,[FirstName] NVARCHAR(25)NOT NULL
	,[LastName]NVARCHAR(25)NOT NULL
	,[Gender] CHAR(1) CHECK ([Gender] IN ('M','F'))
	,[Age] INT NOT NULL
	,[PhoneNumber] CHAR(10) 
	,[CountryId] INT FOREIGN KEY REFERENCES Countries(Id) NOT NULL
)

CREATE TABLE Products
(
	Id INT PRIMARY KEY IDENTITY 
	,[Name] NVARCHAR(25)NOT NULL
	,[Description] NVARCHAR(250)NOT NULL
	,Recipe NVARCHAR(MAX)NOT NULL
	,Price DECIMAL (15,2) NOT NULL CHECK(Price>=0)
)

CREATE TABLE Feedbacks
(
	Id INT PRIMARY KEY IDENTITY 
	,[Description] NVARCHAR(255)
	,[Rate] DECIMAL (4,2) CHECK([Rate]>=0 AND [Rate]<=10) NOT NULL
	,[ProductId] INT FOREIGN KEY REFERENCES Products(Id) NOT NULL
	,[CustomerId] INT FOREIGN KEY REFERENCES Customers(Id) NOT NULL
)

CREATE TABLE Distributors
(
	Id INT PRIMARY KEY IDENTITY 
	,[Name] NVARCHAR(25) UNIQUE 
	,[AddressText]NVARCHAR(30) NOT NULL
	,[Summary] NVARCHAR(200) NOT NULL
	,[CountryId]INT FOREIGN KEY REFERENCES Countries(Id) NOT NULL
)

CREATE TABLE Ingredients
(
	Id INT PRIMARY KEY IDENTITY 
	,[Name] NVARCHAR(30) NOT NULL
	,[Description] NVARCHAR(200) NOT NULL
	,[OriginCountryId] INT FOREIGN KEY REFERENCES Countries(Id) NOT NULL
	,[DistributorId] INT FOREIGN KEY REFERENCES Distributors(Id) NOT NULL
)

CREATE TABLE ProductsIngredients
(
	[ProductId] INT FOREIGN KEY REFERENCES Products(Id) NOT NULL
	,[IngredientId]  INT FOREIGN KEY REFERENCES Ingredients(Id) NOT NULL
	 PRIMARY KEY([ProductId],[IngredientId])
)