--Problem 02  CREATE TABLE 
CREATE TABLE Minions 
	(
		Id INT NOT NULL PRIMARY KEY
		,[Name] VARCHAR(30) NOT NULL
		,Age SMALLINT NOT NULL
	)

CREATE TABLE Towns 
	(
		Id INT NOT NULL PRIMARY KEY
		,[Name] VARCHAR(30)
	)